FROM postgres:latest

RUN apt-get update && apt-get install -y wget build-essential postgresql-server-dev-all

RUN apt-get install -y libpam0g-dev libkrb5-dev

WORKDIR /tmp

RUN git clone https://github.com/ossc-db/pg_bulkload

RUN make && make install
